---
abstract: 'IO::Socket with read/write timeout'
author:
  - "Damien \"dams\" Krotkine"
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Socket-Timeout
provides:
  IO::Socket::Timeout:
    file: lib/IO/Socket/Timeout.pm
    version: 0.15
  PerlIO::via::TimeoutWithReset:
    file: lib/PerlIO/via/TimeoutWithReset.pm
    version: 0.15
requires:
  PerlIO::via::Timeout: 0.23
resources:
  bugtracker: https://github.com/dams/io-socket-timeout/issues
  repository: git://github.com/dams/io-socket-timeout.git
version: 0.15
