---
abstract: 'IO::Socket with read/write timeout'
author:
  - "Damien \"dams\" Krotkine"
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Socket-Timeout
provides:
  IO::Socket::Timeout:
    file: lib/IO/Socket/Timeout.pm
    version: 0.20
  IO::Socket::Timeout::Role::PerlIO:
    file: lib/IO/Socket/Timeout.pm
    version: 0.20
  IO::Socket::Timeout::Role::SetSockOpt:
    file: lib/IO/Socket/Timeout.pm
    version: 0.20
requires:
  PerlIO::via::Timeout: 0.28
resources:
  repository: git://github.com/dams/io-socket-timeout.git
version: 0.20
